<a href="https://colab.research.google.com/github/RiteshopShrivastava/Recommendation_sytem/blob/main/Assignment_Recomendation_System_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Build a recommender system by using cosine similarities score.
Dataset- book.csv

In [5]:
import pandas as pd
import numpy as np

In [114]:
#Read the data set
book_df = pd.read_csv('book.csv', encoding='latin-1')

In [54]:
book_df

      Unnamed: 0  ...  Book.Rating
0              1  ...            5
1              2  ...            3
2              3  ...            6
3              4  ...            8
4              5  ...            6
...          ...  ...          ...
9995        9996  ...            7
9996        9997  ...            9
9997        9998  ...            7
9998        9999  ...            8
9999       10000  ...            6

[10000 rows x 4 columns]

In [15]:
book_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   10000 non-null  int64
 1   User.ID      10000 non-null  int64
 2   Book.Title   10000 non-null  object
 3   Book.Rating  10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

In [115]:
book_data= book_df.iloc[:,1:]

In [116]:
#Rename columns
book_data= book_data.rename({'User.ID': 'User_id','Book.Title':'Book_Title','Book.Rating':'Rating'},axis=1)

In [117]:
# Sorting records by User_id
book_sort = book_data.sort_values('User_id')
book_sort

      User_id                                         Book_Title  Rating
2401        8                                              Wings       5
2400        8  The Western way: A practical guide to the West...       5
2399        8                            Ancient Celtic Romances       5
2402        8                                           Truckers       5
2405        8                                  The Art Of Celtia       7
...       ...                                                ...     ...
2395   278854      La crÃƒÂ³nica del PerÃƒÂº (CrÃƒÂ³nicas de AmÃƒÂ©rica)       7
2398   278854  Celtic Mythology (Library of the World's Myths...       8
2393   278854                         A corrente de Trewis Scott       7
2394   278854                                      As valkÃƒÂ­rias       7
2397   278854     A Treasury of Irish Myth, Legend, and Folklore       6

[10000 rows x 3 columns]

In [58]:
#number of unique users in the dataset
len(book_sort.User_id.unique())

2182

In [59]:
#number of unique book titles in the dataset
len(book_sort.Book_Title.unique())

9659

In [118]:
# Converting long table format into wide format using Pivot Table

user_book = book_sort.pivot_table(index='User_id',columns='Book_Title',values='Rating').reset_index(drop=True)
user_book

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
0                            NaN  ...             NaN
1                            NaN  ...             NaN
2                            NaN  ...             NaN
3                            NaN  ...             NaN
4                            NaN  ...             NaN
...                          ...  ...             ...
2177                         NaN  ...             NaN
2178                         NaN  ...             NaN
2179                         NaN  ...             NaN
2180                         NaN  ...             NaN
2181                         NaN  ...             NaN

[2182 rows x 9659 columns]

In [119]:
user_book.index = book_sort.User_id.unique()

In [120]:
user_book

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
8                            NaN  ...             NaN
9                            NaN  ...             NaN
10                           NaN  ...             NaN
12                           NaN  ...             NaN
14                           NaN  ...             NaN
...                          ...  ...             ...
278846                       NaN  ...             NaN
278849                       NaN  ...             NaN
278851                       NaN  ...             NaN
278852                       NaN  ...             NaN
278854                       NaN  ...             NaN

[2182 rows x 9659 columns]

In [121]:
#Impute NaNs with 0 values
user_book.fillna(0, inplace=True)

In [122]:
user_book.head()

Book_Title   Jason, Madison &amp  ...  Ãƒ?Ã‚?bermorgen.
8                            0.0  ...             0.0
9                            0.0  ...             0.0
10                           0.0  ...             0.0
12                           0.0  ...             0.0
14                           0.0  ...             0.0

[5 rows x 9659 columns]

In [95]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [123]:
user_sim = 1- pairwise_distances( user_book.values,metric='cosine')

In [124]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [125]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)

In [126]:
user_sim_df.iloc[0:10,0:10]

     0    1    2    3    4    5    6    7    8    9
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [127]:
#Set the index and column names to user ids 
user_sim_df.index = book_data.User_id.unique()
user_sim_df.columns = book_data.User_id.unique()

In [128]:
user_sim_df.iloc[0:10,0:10]

        276726  276729  276736  276737  ...  276747  276748  276751  276754
276726     1.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0  ...     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     1.0  ...     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276745     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
276747     0.0     0.0     0.0     0.0  ...     1.0     0.0     0.0     0.0
276748     0.0     0.0     0.0     0.0  ...     0.0     1.0     0.0     0.0
276751     0.0     0.0     0.0     0.0  ...     0.0     0.0     1.0     0.0
276754     0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     1.0

[10 rows x 10 columns]

In [129]:
#fill diagonal values with zero
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [130]:
#Most Similar Users
user_sim_df.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [131]:
#searching data of specific user id
book_data[(book_data['User_id']==162113) | (book_data['User_id']==161453)]

      User_id                                         Book_Title  Rating
8959   161453  Bread, Tomato, Garlic: Quick Cooking With 3 Ma...       9
8960   161453  The Ubiquitous Shrimp: From Simple to Exotic, ...       8
9989   162113       The Cape Ann (Contemporary American Fiction)       8

In [132]:
user_1=book_data[book_data['User_id']==161453]

In [133]:
user_2=book_data[book_data['User_id']==162113]

In [134]:
#Books purchased by user 1
user_1.Book_Title

8959    Bread, Tomato, Garlic: Quick Cooking With 3 Ma...
8960    The Ubiquitous Shrimp: From Simple to Exotic, ...
Name: Book_Title, dtype: object

In [92]:
#Books purchased by user 2
user_2.Book_Title

9989    The Cape Ann (Contemporary American Fiction)
Name: Book_Title, dtype: object

In [135]:
#Extracting records of both the users using outer join
pd.merge(user_1,user_2,on='Book_Title',how='outer')

   User_id_x  ... Rating_y
0   161453.0  ...      NaN
1   161453.0  ...      NaN
2        NaN  ...      8.0

[3 rows x 5 columns]

**Inference :**
1. User-161453 can be recomended books which are purchased by user-162113 i.e 'The Cape Ann (Contemporary American Fiction)'
2. User-162113 can be recomended books which are purchased by user-161453 i.e 'Bread, Tomato, Garlic: Quick Cooking With 3 Ma..' & 'The Cape Ann (Contemporary American Fiction)'


Likewise recomendations can be made to other users also.